services:
  api:
    build: .
    container_name: ecommerce-recommender
    ports:
      - "8000:8000"
    volumes:
    # Mount data directories
      - ./products:/app/products
      - ./model:/app/model
